[build]
builder = "nixpacks"

[deploy]
startCommand = "cd src/backend && python railway_start.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "src/backend"
